title: omokagbo.com
author: omokagbo
email: emmanuel.omokagbo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site, I plan to talk about my journey into
  the tech world. From electrical engineering to front end 
  development and iOS development. I also plan to talk about 
  some of my lazy hobbies which you will get to know about 
  in time. For now, sit tight and enjoy the ride.
  
theme: minima

# social links
twitter_username: omokagboEM # DO NOT include the @ character, or else the build will fail!
github_username:  omokagbo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
